stages:
  - build
  - test
  - deploy

variables:
  GO_VERSION: '1.18'  # Make sure this version exists

before_script:
  - apt-get update -qy
  - apt-get install -y wget
  - wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz
  - tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin

build:
  stage: build
  image: golang:$GO_VERSION
  script:
    - go build -v ./...
  artifacts:
    paths:
      - project_name

test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - go test -v ./...

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.domain.com
  script:
    - docker build -t project_name-go .
    - docker tag project_name-go:latest "registry.domain.com/project_name/project_name-go:$CI_COMMIT_TAG"
    - docker push "registry.domain.com/project_name/project_name-go:$CI_COMMIT_TAG"
  only:
    - tags
