version: '3.8'
services:
  app:
    container_name: project_name
    build: .
    environment:
      - CONFIG_PATH=./config
      - APP_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - go-network
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - go-network

#config volume
volumes:
  db-data:
    driver: local

#network config
networks:
  go-network:
    driver: bridge